package model;

public class Darbuotojas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String pavarde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String pareigos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String viesbutis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Darbuotojas.ID
     *
     * @return the value of Darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Darbuotojas.ID
     *
     * @param id the value for Darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Darbuotojas.Vardas
     *
     * @return the value of Darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Darbuotojas.Vardas
     *
     * @param vardas the value for Darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Darbuotojas.Pavarde
     *
     * @return the value of Darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Darbuotojas.Pavarde
     *
     * @param pavarde the value for Darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Darbuotojas.Pareigos
     *
     * @return the value of Darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getPareigos() {
        return pareigos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Darbuotojas.Pareigos
     *
     * @param pareigos the value for Darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setPareigos(String pareigos) {
        this.pareigos = pareigos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Darbuotojas.Viesbutis
     *
     * @return the value of Darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getViesbutis() {
        return viesbutis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Darbuotojas.Viesbutis
     *
     * @param viesbutis the value for Darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setViesbutis(String viesbutis) {
        this.viesbutis = viesbutis;
    }
}