package model;

public class Viesbutis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String kodas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String pavadinimas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    private String adresas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Viesbutis.Kodas
     *
     * @return the value of Viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getKodas() {
        return kodas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Viesbutis.Kodas
     *
     * @param kodas the value for Viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setKodas(String kodas) {
        this.kodas = kodas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Viesbutis.Pavadinimas
     *
     * @return the value of Viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Viesbutis.Pavadinimas
     *
     * @param pavadinimas the value for Viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Viesbutis.Adresas
     *
     * @return the value of Viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public String getAdresas() {
        return adresas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Viesbutis.Adresas
     *
     * @param adresas the value for Viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 10:40:42 EEST 2017
     */
    public void setAdresas(String adresas) {
        this.adresas = adresas;
    }
}