package mybatis.dao;

import java.util.List;
import mybatis.model.Darbuotojas;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DarbuotojasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotojas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotojas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int insert(Darbuotojas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotojas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    Darbuotojas selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotojas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    List<Darbuotojas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotojas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int updateByPrimaryKey(Darbuotojas record);
}