package mybatis.dao;

import java.util.List;
import mybatis.model.DarbuotojuSuniukuSarasas;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DarbuotojuSuniukuSarasasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotoju_Suniuku_Sarasas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int deleteByPrimaryKey(@Param("suniukoid") String suniukoid, @Param("darbuotojoid") String darbuotojoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotoju_Suniuku_Sarasas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int insert(DarbuotojuSuniukuSarasas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Darbuotoju_Suniuku_Sarasas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    List<DarbuotojuSuniukuSarasas> selectAll();
}