package mybatis.dao;

import java.util.List;
import mybatis.model.Viesbutis;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ViesbutisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int deleteByPrimaryKey(String kodas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int insert(Viesbutis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    Viesbutis selectByPrimaryKey(String kodas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    List<Viesbutis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    int updateByPrimaryKey(Viesbutis record);
}