package mybatis.model;

public class Suniukas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    private String gyvunoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    private String veisle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    private String viesbutis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suniukas.GyvunoID
     *
     * @return the value of Suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public String getGyvunoid() {
        return gyvunoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suniukas.GyvunoID
     *
     * @param gyvunoid the value for Suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public void setGyvunoid(String gyvunoid) {
        this.gyvunoid = gyvunoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suniukas.Vardas
     *
     * @return the value of Suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suniukas.Vardas
     *
     * @param vardas the value for Suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suniukas.Veisle
     *
     * @return the value of Suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public String getVeisle() {
        return veisle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suniukas.Veisle
     *
     * @param veisle the value for Suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public void setVeisle(String veisle) {
        this.veisle = veisle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suniukas.Viesbutis
     *
     * @return the value of Suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public String getViesbutis() {
        return viesbutis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suniukas.Viesbutis
     *
     * @param viesbutis the value for Suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 00:59:06 EEST 2017
     */
    public void setViesbutis(String viesbutis) {
        this.viesbutis = viesbutis;
    }
}